spring:
    datasource:
        url: jdbc:mysql://localhost:3306/jumso?serverTimezone=Asia/Seoul
        password: ${database.password}

    redis:
        host: localhost
        port: 6379
        username: jumso
        password: ${redis.password}

    config:
        import: 'aws-parameterstore:'
        activate:
            on-profile: local

    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            # topic
            topic: KAFKA_CHAT_SERVER-${server.port}
            # group
            group-id: KAFKA_CHAT_SERVER-${server.port}
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        email-server-port: ${email.port}

server:
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true

# JWT
jwt:
    secret: ${jwt.secret}

# p6spy
decorator:
    datasource:
        p6spy:
            enable-logging: true
