spring:
    application:
        name: jumso-chat

    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# JWT
jwt:
    issuer: jumso
    token:
        access:
#            expiration: 86_400_000 # 1일
            expiration: 3_600_000 # 1시간
            header: Authorization
        refresh:
#            expiration: 604_800_000 # 7? (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> d) * 7L(d -> w))
            expiration: 86_400_000 # 1일
            header: AuthorizationRefresh

aws:
    paramstore:
        enabled: true
        prefix: /Jumso
        name: chat
        profileSeparator: _
