version: '3'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        ports:
            - "2181:2181"
        restart: always
        networks:
            - production_network
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            TZ: Asia/Seoul

    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        restart: always
        networks:
            - production_network
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            TZ: Asia/Seoul

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - /redis/redis.conf:/usr/local/etc/redis/redis.conf
            - /redis/users.acl:/usr/local/etc/redis/users.acl
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        restart: always
        networks:
            - production_network
        environment:
            TZ: Asia/Seoul

    mysql:
        image: mysql:8.0.39
        platform: linux/amd64
        container_name: mysql
        ports:
            - "3306:3306"
        restart: always
        networks:
            - production_network
        environment:
            MYSQL_ROOT_PASSWORD: #password
            TZ: Asia/Seoul
        volumes:
#            - /mysql/mysql.cnf:/etc/mysql/my.cnf
            - /mysql/cert/jenkins.jumso.life:/etc/mysql/cert
        command: ["--ssl-ca=/etc/mysql/cert/fullchain1.pem", "--ssl-cert=/etc/mysql/cert/cert.pem", "--ssl-key=/etc/mysql/cert/privkey.pem"]

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        networks:
            - production_network
        volumes:
            - /nginx/conf/default.conf:/etc/nginx/sites-enabled/default.conf
            - /nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt
        restart: always
        environment:
            TZ: Asia/Seoul

    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        hostname: jenkins
        ports:
            - "8080:8080"
        expose:
            - "8080"
        networks:
            - production_network
        volumes:
            - /jenkins/jenkins_home:/var/jenkins_home
            - /nginx/conf:/nginx/conf
        restart: always
        environment:
            TZ: Asia/Seoul

networks:
    production_network:
        driver: bridge
