version: '3'

services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        hostname: jenkins
        ports:
            - "8080:8080"
        expose:
            - "8080"
        networks:
            - production_network
        volumes:
            - /jenkins/jenkins_home:/var/jenkins_home
            - /nginx/conf:/nginx/conf
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        environment:
            TZ: Asia/Seoul

networks:
    production_network:
        driver: bridge
