version: '3'

services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        networks:
            - production_network
        volumes:
            - /nginx/conf/sites-enabled:/etc/nginx/sites-enabled
            - /nginx/nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt
        restart: always
        environment:
            TZ: Asia/Seoul

networks:
    production_network:
        driver: bridge
