spring:
    mail:
        password: ${mail.password}

    config:
        import: 'aws-parameterstore:'
        activate:
            on-profile: prod

    kafka:
        bootstrap-servers: kafka:9092
        consumer:
            # topic
            topic: KAFKA_EMAIL_SERVER
            # group
            group-id: KAFKA_EMAIL_SERVER
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true

# p6spy
decorator:
    datasource:
        p6spy:
            enable-logging: true
