spring:
    mail:
        password: ${mail.password}

    config:
        import: 'aws-parameterstore:'
        activate:
            on-profile: prod

server:
    port: 9090
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true

# p6spy
decorator:
    datasource:
        p6spy:
            enable-logging: true
