spring:
    application:
        name: jumso-email

    mail:
        host: smtp.gmail.com
        port: 587
        username: jumso.official@gmail.com
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

aws:
    paramstore:
        enabled: true
        prefix: /Jumso
        name: email
        profileSeparator: _
