spring:
    mail:
        password: ${mail.password}

    config:
        import: 'aws-parameterstore:'
        activate:
            on-profile: local

    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            # topic
            topic: KAFKA_EMAIL_SERVER-7001
            # group
            group-id: KAFKA_EMAIL_SERVER-7001
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true

# p6spy
decorator:
    datasource:
        p6spy:
            enable-logging: true
