spring:
    datasource:
        url: jdbc:mysql://mysql/jumso?serverTimezone=Asia/Seoul
        password: ${database.password}

    redis:
        host: redis
        port: 6379
        username: jumso
        password: ${redis.password}

    config:
        import: 'aws-parameterstore:'
        activate:
            on-profile: prod

    kafka:
        bootstrap-servers: kafka:9092
        email-server-port: ${email.port}

server:
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true

# JWT
jwt:
    secret: ${jwt.secret}

# p6spy
decorator:
    datasource:
        p6spy:
            enable-logging: true
